const fs = require('fs');

let content = fs.readFileSync('bot.js', 'utf8');

const dict = [
  ['PHÁT HIỆN:', 'DETECTED:'],
  ['Dừng ngay lập tức!', 'Stopping immediately!'],
  ['BOT KHỞI ĐỘNG', 'BOT STARTED'],
  ['Tạo thư mục session:', 'Created session directory:'],
  ['Bot khởi động hoàn tất!', 'Bot started successfully!'],
  ['Khởi tạo trình duyệt (persistent context) at', 'Initializing browser (persistent context) at'],
  ['Session tồn tại — bỏ qua đăng nhập', 'Session exists — skipping login'],
  ['LẦN CHẠY ĐẦU TIÊN — CẦN ĐĂNG NHẬP THỦ CÔNG', 'FIRST RUN — MANUAL LOGIN REQUIRED'],
  ['1. Trình duyệt sẽ mở Google Maps', '1. Browser will open Google Maps'],
  ['2. Đăng nhập vào tài khoản Google quản lý Business', '2. Log in to your Google Business account'],
  ['3. Sau khi đăng nhập xong, nhấn ENTER ở terminal', '3. After logging in, press ENTER in the terminal'],
  ['Đang chờ bạn đăng nhập... Nhấn ENTER khi xong.', 'Waiting for login... Press ENTER when done.'],
  ['Đã nhận tín hiệu — tiếp tục...', 'Signal received — continuing...'],
  ['Session đã được lưu. Lần chạy sau sẽ tự động đăng nhập.', 'Session saved. Future runs will auto-login.'],
  ['Đang quét:', 'Scanning:'],
  ['tổng cộng', 'total'],
  ['review mới', 'new review(s)'],
  ['Lỗi khi quét', 'Error scanning'],
  ['Tìm tab Reviews...', 'Looking for Reviews tab...'],
  ['Đánh giá', 'Review'],
  ['đánh giá', 'review'],
  ['có thể đã ở trang reviews', 'might already be on reviews page'],
  ['Sắp xếp', 'Sort'],
  ['sắp xếp', 'sort'],
  ['phù hợp nhất', 'most relevant'],
  ['Mới nhất', 'Newest'],
  ['mới nhất', 'newest'],
  ['Đã thử sắp xếp theo Mới nhất', 'Attempted to sort by Newest'],
  ['lần', 'times'],
  ['Lỗi scroll:', 'Scroll error:'],
  ['Phản hồi từ chủ sở hữu', 'Response from the owner'],
  ['Trả lời từ chủ sở hữu', 'Response from the owner'],
  ['Không thể scroll tới review', 'Cannot scroll to review'],
  ['phản hồi', 'reply'],
  ['trả lời', 'reply'],
  ['Trở lời công khai', 'Replying publicly'],
  ['Có thể form bị chặn hoặc chưa hiển thị.', 'Form might be blocked or not visible.'],
  ['Click trực tiếp bằng XPath chính xác (Force Click)', 'Clicking directly with precise XPath (Force Click)'],
  ['theo đường dẫn XPath chính xác', 'via precise XPath'],
  ['Đăng', 'Post'],
  ['gửi', 'send'],
  ['đăng', 'post'],
  ['Quét tất cả các frames (đối với form iframe)', 'Scanning all frames (for iframe form)'],
  ['Evaluate fallback trên trang chính', 'Evaluate fallback on main page'],
  ['Thử tìm nút có class đặc thù của Google Maps (thường là nút màu xanh)', 'Trying to find specific Google Maps class button (usually blue button)'],
  ['Có thể do mạng chậm', 'Might be due to slow network'],
  ['KIỂM TRA MÀN HÌNH "TẤT CẢ ĐÃ TRẢ LỜI" ("All caught up")', 'CHECK FOR "ALL CAUGHT UP" SCREEN'],
  ['Bạn đã cập nhật tất cả', 'You are all caught up'],
  ['Làm tốt lắm! Bạn không còn bài đánh giá nào để trả lời nữa.', 'Great job! You have no more reviews to reply to.'],
  ['Thử bấm OK button để thoát', 'Try clicking OK button to exit'],
  ['Dừng lặp...', 'Stopping loop...'],
  ['Đợi nghỉ 3 phút khi All caught up theo yêu cầu', 'Waiting 3 minutes when All caught up as requested'],
  ['Thoát vòng lặp hiện tại', 'Exiting current loop'],
  ['Tạm thoát vòng lặp để retry.', 'Breaking loop to retry.'],
  ['Không tìm thấy ô nhập content và cũng không thấy thông báo All caught up.', 'Cannot find input field and no All caught up message.'],
  ['Đã điền content xong, đợi 1 giây trước khi bấm', 'Content filled, waiting 1 second before clicking'],
  ['Không thể ấn duyệt', 'Cannot click Submit'],
  ['Tăng lỗi và break.', 'Increasing error count and breaking.'],
  ['Đợi 1 giây sau khi bấm', 'Waiting 1s after pressing'],
  ['Đã bấm', 'Clicked'],
  ['Chờ', 'Wait'],
  ['giây để sang preview nội dung review mới...', 'seconds to preview next review...'],
  ['phiên Modal', 'Modal session'],
  ['Đọc maps.txt để lấy link (dễ nhất cho người mới).', 'Read maps.txt to get links (easiest for beginners).'],
  ['Đọc file, xử lý lỗi encoding (UTF-16 từ PowerShell) hoặc BOM thừa', 'Read file, handle encoding errors (UTF-16 from PowerShell) or BOM'],
  ['Fix lỗi sinh ra từ lệnh echo trên Windows', 'Fix errors caused by Windows echo command'],
  ['Xóa ký tự BOM ẩn', 'Remove hidden BOM character'],
  ['Tìm xem có tên Map không, ví dụ:', 'Check if map name exists, example:'],
  ['Format lại tên map có chứa số thứ tự', 'Reformat map name containing index'],
  ['Xoá số đằng trước nếu đã từng có dạng [X] để tránh lặp [1] [1]', 'Remove previous index format [X] to prevent duplicate [1] [1]'],
  ['Nếu url là HTTP hợp lệ', 'If URL is valid HTTP'],
  ['phút', 'minute(s)'],
  ['Làm mới reply templates from Google Sheet...', 'Refreshing reply templates from Google Sheet...'],
  ['Gửi reload phòng lag mạng/DOM', 'Send reload to prevent network/DOM lag'],
  ['Nếu không có trong maps.txt, fallback sang config.json', 'If not in maps.txt, fallback to config.json'],
  ['CLI Menu CHỌN MAP', 'CLI Menu CHOOSE MAP'],
  ['mỗi map 1 trình duyệt', '1 browser per map'],
  ['nhận được — đang tắt bot...', 'received — shutting down bot...'],
  ['MODE: Run ALL maps in PARALLEL (mỗi map 1 browser riêng)', 'MODE: Run ALL maps in PARALLEL (1 separate browser per map)'],
  ['Tạo 1 ReviewBot riêng cho mỗi map', 'Create 1 separate ReviewBot for each map'],
  ['Khởi động tất cả các bot song song', 'Start all bots in parallel'],
  ['lệch nhau 3 giây', 'staggered by 3 seconds'],
  ['để tránh mở quá nhiều browser cùng lúc', 'to prevent opening too many browsers at once'],
  ['nhận được — đang tắt tất cả', 'received — shutting down all'],
  ['bot...', 'bots...'],
  ['Chờ tất cả các bot chạy (sẽ không bao giờ resolve vì mỗi bot loop vô hạn)', 'Wait for all bots to run (will never resolve since each bot loops indefinitely)'],
  ['Lỗi khởi động bot:', 'Error starting bot:'],
  ['Đang tắt bot...', 'Shutting down bot...'],
  ['Browser đã đóng', 'Browser closed'],
  ['Lỗi khi đóng browser:', 'Error closing browser:'],
  ['Bot đã tắt hoàn toàn.', 'Bot has shut down completely.'],
  ['Khởi động bot riêng...', 'Starting separate bot...'],
  ['Trở lời công khai', 'Replying publicly'],
  ['Gõ chậm như người bằng keyboard chung', 'Typing slowly like a human using standard keyboard'],
  ['tăng số lần cuộn để quét khoảng 50+ review', 'increase scroll count to scan ~50+ reviews']
];

for (const [vi, en] of dict) {
  content = content.split(vi).join(en);
}

fs.writeFileSync('bot.js', content, 'utf8');
console.log('Translated successfully!');
